### ISSUE TITLE
Python winusb module?

### ISSUE THREAD

**Issue by KWolfe81** [felHR85/WinUsbPy#5]
How do I install the required winusb module?

```Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import winusbpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Code\Valve\Watchman\iso\WinUsbPy-master\WinUsbPy-master\winusbpy\__init__.py", line 4, in <module>
    from winusb import *
ModuleNotFoundError: No module named 'winusb'```

**Comment by rundekugel** [comment]
python setup.py install
